apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata: {name: block-stale-images-exceptions}
context: ../.kyverno-test/context.yaml
policies: [../block-stale-images.yaml]
resources: [../.kyverno-test/bad.yaml, ../.kyverno-test/good.yaml]
exceptions: [../.kyverno-test/exceptions.yaml]
results:
- {kind: Pod, policy: block-stale-images, resources: [redis-bad], result: pass, isValidatingPolicy: true}
- {kind: Pod, policy: block-stale-images, resources: [redis-good], result: pass, isValidatingPolicy: true}
