apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: tolerations-exception
  namespace: policy-exceptions
spec:
  policyRefs: [{kind: MutatingPolicy, name: add-tolerations}]
  matchConditions:
  - name: exact-resource
    expression: object.metadata.?namespace.orValue('') == '' && object.metadata.name == 'addpod01'
