apiVersion: v1
kind: Pod
metadata:
  name: partial-exception
  namespace: default
  annotations:
    kyverno.io/baseimages1: cgr.dev/chainguard/static:latest
    kyverno.io/baseimages2: cgr.dev/chainguard/static:latest
spec:
  containers:
  - name: first
    image: registry.invalid/exempt:1
  - name: middle
    image: ghcr.io/kyverno/kyverno:v1.9.0
  - name: last
    image: ghcr.io/kyverno/kyverno:v1.9.0
