apiVersion: v1
kind: Pod
metadata:
  name: image-exception-pod
  namespace: team-a
spec:
  containers:
  - name: first
    image: registry.example/skip-first:1
  - name: middle
    image: registry.example/mutate-middle:1
    env:
    - name: HTTP_PROXY
      value: http://proxy.corp.domain:8080
    - name: HTTPS_PROXY
      value: https://secureproxy.corp.domain:8080
    - name: NO_PROXY
      value: localhost,*.example.com
  - name: last
    image: registry.example/skip-last:1
