apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: restrict-seccomp-strict
  annotations:
    policies.kyverno.io/title: Restrict Seccomp (Strict) in ValidatingPolicy
    policies.kyverno.io/category: Pod Security Standards (Restricted) in ValidatingPolicy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.19.1
    kyverno.io/kyverno-version: 1.14.0
    kyverno.io/kubernetes-version: "1.30+"
    policies.kyverno.io/description: >-
      The seccomp profile in the Restricted group must not be explicitly set to Unconfined
      but additionally must also not allow an unset value. This policy, 
      requiring Kubernetes v1.30 or later, ensures that seccomp is 
      set to `RuntimeDefault` or `Localhost`. A known issue prevents a policy such as this
      using `anyPattern` from being persisted properly in Kubernetes 1.23.0-1.23.2.
spec:
  validationActions:
     - Audit
  evaluation:
    background:
      enabled: true
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["pods", "replicationcontrollers"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["jobs", "cronjobs"]
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["UPDATE"]
      resources: ["pods/ephemeralcontainers"]
  variables:
    - name: podSpec
      expression: >-
        object.spec.?jobTemplate.?spec.?template.?spec.orValue(
        object.spec.?template.?spec.orValue(object.spec))
    - name: allContainers
      expression: >-
        variables.podSpec.containers +
        variables.podSpec.?initContainers.orValue([]) +
        variables.podSpec.?ephemeralContainers.orValue([])
  validations:
  - expression: >- 
      variables.podSpec.?os.?name.orValue('linux') == 'windows' ||
      variables.allContainers.all(container,
        (container.image in exceptions.allowedImages && has(container.securityContext) && has(container.securityContext.seccompProfile)) ||
        (has(container.securityContext) && has(container.securityContext.seccompProfile) &&
        (container.securityContext.seccompProfile.?type.orValue('') in ['RuntimeDefault', 'Localhost'] ||
        ('seccomp.type:' + container.securityContext.seccompProfile.?type.orValue('')) in exceptions.allowedValues)) ||
        (has(variables.podSpec.securityContext) && has(variables.podSpec.securityContext.seccompProfile) &&
        (!has(container.securityContext) || !has(container.securityContext.seccompProfile)))) &&
      ((has(variables.podSpec.securityContext) && has(variables.podSpec.securityContext.seccompProfile) &&
        (variables.podSpec.securityContext.seccompProfile.?type.orValue('') in ['RuntimeDefault', 'Localhost'] ||
        ('seccomp.type:' + variables.podSpec.securityContext.seccompProfile.?type.orValue('')) in exceptions.allowedValues)) ||
       ((!has(variables.podSpec.securityContext) || !has(variables.podSpec.securityContext.seccompProfile)) &&
        variables.allContainers.all(container, (container.image in exceptions.allowedImages && has(container.securityContext) && has(container.securityContext.seccompProfile)) ||
        (has(container.securityContext) && has(container.securityContext.seccompProfile) &&
        (container.securityContext.seccompProfile.?type.orValue('') in ['RuntimeDefault', 'Localhost'] ||
        ('seccomp.type:' + container.securityContext.seccompProfile.?type.orValue('')) in exceptions.allowedValues)))))
    message: >-
      seccompProfile.type must be either 'RuntimeDefault' or 'Localhost'.
