apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: restrict-annotations-exception
policies: [../restrict-annotations.yaml]
resources: [../.kyverno-test/resource.yaml]
exceptions: [../.kyverno-test/exception.yaml]
results:
- isValidatingPolicy: true
  kind: Pod
  policy: restrict-annotations
  resources: [default/myapp-pod]
  result: pass
- isValidatingPolicy: true
  kind: Deployment
  policy: restrict-annotations
  resources: [default/mydeploy]
  result: fail
