apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: require-ingress-https-exception
policies: [../require-ingress-https.yaml]
resources: [../.kyverno-test/resource.yaml]
exceptions: [../.kyverno-test/exception.yaml]
results:
- isValidatingPolicy: true
  kind: Ingress
  policy: require-ingress-https
  resources: [default/badingress01]
  result: skip
- isValidatingPolicy: true
  kind: Ingress
  policy: require-ingress-https
  resources: [default/badingress02]
  result: fail
