apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: required-annotation-partial
  namespace: policy-exceptions
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: require-annotations
  matchConditions:
  - name: exact-resource
    expression: request.namespace == 'policy-exceptions' && request.name == 'badcronjob01'
  allowedValues:
  - missing-annotation:corp.org/department
