apiVersion: v1
kind: Pod
metadata:
  name: pod01
  namespace: bkc-podlabel-ns
spec:
  containers:
    - name: busybox
      image: busybox:1.35
      command: [ "/bin/sh", "-c" ]
      args:
        - echo expected-cp-content >/test1.txt; sleep 3600
