apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata: {name: ingress-controller-exceptions}
policies: [../check-ingress-nginx-controller-version-and-annotation-policy.yaml]
resources: [resource.yaml]
exceptions: [../.kyverno-test/exceptions.yaml]
results:
- isValidatingPolicy: true
  kind: Pod
  policy: check-ingress-nginx-controller-version-and-annotation-policy
  resources: [policy-exceptions/bad-pod]
  result: pass
