apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: default-namespace-exception
  namespace: policy-exceptions
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: disallow-default-namespace
  allowedValues: [namespace:default]
  matchConditions:
  - name: exact-resource
    expression: object.kind == 'Pod' && object.metadata.name == 'exception-default-namespace' && object.metadata.namespace == 'default'
