apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: disallow-latest-tag
policies:
- ../disallow-latest-tag.yaml
resources:
- resource.yaml
exceptions:
- exceptions.yaml
results:
- isValidatingPolicy: true
  kind: Deployment
  policy: disallow-latest-tag
  resources:
  - baddeployment01
  result: fail
- isValidatingPolicy: true
  kind: Pod
  policy: disallow-latest-tag
  resources:
  - badpod01
  - badpod02
  result: fail
- isValidatingPolicy: true
  kind: Deployment
  policy: disallow-latest-tag
  resources:
  - gooddeployment01
  result: pass
- isValidatingPolicy: true
  kind: Pod
  policy: disallow-latest-tag
  resources:
  - exception-latest-pod
  result: pass
- isValidatingPolicy: true
  kind: Pod
  policy: disallow-latest-tag
  resources:
  - myapp-pod
  - registry-port-pod
  - ipv6-registry-pod
  result: pass
- isValidatingPolicy: true
  kind: Pod
  policy: disallow-latest-tag
  resources:
  - init-latest-pod
  - ephemeral-latest-pod
  result: fail
- isValidatingPolicy: true
  kind: Deployment
  policy: disallow-latest-tag
  resources:
  - vit-baddeployment01
  result: fail
- isValidatingPolicy: true
  kind: Pod
  policy: disallow-latest-tag
  resources:
  - vit-badpod01
  - vit-badpod02
  result: fail
- isValidatingPolicy: true
  kind: StatefulSet
  policy: disallow-latest-tag
  resources: [badstatefulset01]
  result: fail
- isValidatingPolicy: true
  kind: DaemonSet
  policy: disallow-latest-tag
  resources: [baddaemonset01]
  result: fail
- isValidatingPolicy: true
  kind: ReplicaSet
  policy: disallow-latest-tag
  resources: [badreplicaset01]
  result: fail
- isValidatingPolicy: true
  kind: Job
  policy: disallow-latest-tag
  resources: [badjob01]
  result: fail
- isValidatingPolicy: true
  kind: CronJob
  policy: disallow-latest-tag
  resources: [badcronjob01]
  result: fail
- isValidatingPolicy: true
  kind: ReplicationController
  policy: disallow-latest-tag
  resources: [badreplicationcontroller01]
  result: fail
