apiVersion: v1
kind: Pod
metadata:
  name: exception-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/middle: runtime/default
spec:
  containers:
  - name: first
    image: exempt.example/first:1
  - name: middle
    image: mutate.example/middle:1
  - name: last
    image: exempt.example/last:1
