# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: application-prevent-default-project
spec:
  template: false
  steps:
    - name: shared-exception-namespace
      skipDelete: true
      try:
      - apply:
          file: exception-namespace.yaml
    - name: step-01
      try:
        - assert:
            file: crd-assert.yaml
        - apply:
            file: rbac.yaml
    - name: step-02
      try:
        - apply:
            file: ../application-prevent-default-project.yaml
        - patch:
            resource:
              apiVersion: policies.kyverno.io/v1
              kind: ValidatingPolicy
              metadata:
                name: application-prevent-default-project
              spec:
                validationActions: [Deny]
        - assert:
            file: policy-ready.yaml
    - name: step-03
      try:
       - apply:
           file: good-application.yaml
       - apply:
           expect:
             - check:
                 (contains($error, 'Policy application-prevent-default-project failed') && contains($error, 'The default project may not be used in an Application.')): true
           file: bad-application.yaml
    - name: exact-exception
      try:
      - apply:
          file: exception.yaml
      - apply:
          file: exception-application.yaml
      - apply:
          expect:
            - check:
                (contains($error, 'Policy application-prevent-default-project failed') && contains($error, 'The default project may not be used in an Application.')): true
          file: empty-application.yaml
      - apply:
          expect:
            - check:
                "(contains($error, 'spec.project: Required value'))": true
          file: missing-project-application.yaml
      - delete:
          file: exception.yaml
      - delete:
          file: exception-application.yaml
      - apply:
          expect:
            - check:
                (contains($error, 'Policy application-prevent-default-project failed') && contains($error, 'The default project may not be used in an Application.')): true
          file: exception-application.yaml
