# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  creationTimestamp: null
  name: block-pod-exec-by-pod-label
spec:
  steps:
  - name: shared-exception-namespace
    skipDelete: true
    try:
    - apply:
        file: policy-exceptions-namespace.yaml
  - name: step-01
    try:
    - apply:
        file: ../block-pod-exec-by-pod-label.yaml
    - patch:
        resource:
          apiVersion: policies.kyverno.io/v1
          kind: ValidatingPolicy
          metadata:
            name: deny-exec-by-pod-label
          spec:
            validationActions:
            - Deny
    - assert:
        file: policy-ready.yaml
  - name: step-02
    try:
    - apply:
        file: ns.yaml
    - apply:
        file: pods.yaml
  - name: step-03
    try:
    - sleep:
        duration: 5s
  - name: step-04
    try:
    - script:
        content: if kubectl exec -n bpe-podlabel-ns pod03 -- ls; then exit 1;else
          exit 0; fi
    - script:
        content: kubectl exec -n bpe-podlabel-ns pod01 -- ls
    - script:
        content: kubectl exec -n bpe-podlabel-ns pod02 -- ls
    - script:
        content: kubectl exec -n bpe-podlabel-ns pod04 -- ls
  - name: step-05
    try:
    - apply:
        file: exceptions.yaml
    - script:
        content: kubectl exec -n bpe-podlabel-ns pod03 -- ls
  - name: step-06
    try:
    - delete:
        file: exceptions.yaml
    - script:
        content: if kubectl exec -n bpe-podlabel-ns pod03 -- ls; then exit 1; else exit 0; fi
  - name: step-99
    try:
    - script:
        content: kubectl delete all --all --force --grace-period=0 -n bpe-podlabel-ns
