apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: skip-imagepullsecret-images
  namespace: policy-exceptions
spec:
  policyRefs:
  - name: add-imagepullsecrets
    kind: MutatingPolicy
  images:
  - corp.reg.com/skip-first:1
  - corp.reg.com/skip-last:1
  matchConditions:
  - name: target-pod
    expression: object.metadata.namespace == 'team-a' && object.metadata.name == 'image-exception-pod'
