apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: add-volume
policies:
- ../add-certificates-volume.yaml
resources:
- resource.yaml
- exception-resource.yaml
exceptions:
- exception.yaml
results:
- kind: Pod
  patchedResources: patchedResource.yaml
  policy: add-certificates-volume
  resources:
  - mypod
  result: pass
  isMutatingPolicy: true
- kind: Pod
  patchedResources: exception-patched.yaml
  policy: add-certificates-volume
  resources: [exception-pod]
  result: pass
  isMutatingPolicy: true
