apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: stable-api-fixture
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  distinguisherMethod:
    type: ByUser
  rules:
  - subjects:
    - kind: Group
      group:
        name: system:authenticated
    resourceRules:
    - verbs: [get]
      apiGroups: [""]
      resources: [pods]
      clusterScope: true
