apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: imagepullsecrets-exception
  namespace: policy-exceptions
spec:
  policyRefs: [{kind: MutatingPolicy, name: add-imagepullsecrets-for-containers-and-initcontainers}]
  matchConditions:
  - name: exact-resource
    expression: object.metadata.?namespace.orValue('') == '' && object.metadata.name == 'myapp-pod-1'
