apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: skip-emptydir-pod
  namespace: policy-exceptions
spec:
  policyRefs: [{kind: MutatingPolicy, name: add-emptydir-sizelimit}]
  matchConditions:
  - name: exact-target
    expression: object.metadata.?namespace.orValue('') == 'default' && object.metadata.name == 'exception-pod'
