apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: add-default-securitycontext
policies:
- ../add-default-securitycontext.yaml
resources:
- resource.yaml
- exception-resource.yaml
exceptions:
- exception.yaml
results:
- kind: Pod
  patchedResources: patchedResource.yaml
  policy: add-default-securitycontext
  resources:
  - myapp-pod
  result: pass
  isMutatingPolicy: true
- kind: Pod
  policy: add-default-securitycontext
  resources: [exception-pod]
  result: skip
  isMutatingPolicy: true
