apiVersion: v1
kind: Pod
metadata: {name: badpod03, namespace: policy-exceptions}
spec:
  containers:
  - name: app
    image: busybox:1.35
    livenessProbe:
      exec: {command: [echo, 'ps -aux | grep cala']}
