apiVersion: v1
kind: Pod
metadata: {name: exception-pod, namespace: team-a}
spec:
  containers:
  - {name: first, image: registry.example/skip-first:1}
  - name: middle
    image: registry.example/mutate-middle:1
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {drop: [ALL]}
      privileged: false
  - {name: last, image: registry.example/skip-last:1}
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile: {type: RuntimeDefault}
