apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: protected-service-exception
  namespace: policy-exceptions
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: block-updates-deletes
  matchConditions:
  - name: target-namespace
    expression: request.namespace == 'block-updates-deletes-ns'
  - name: target-name
    expression: request.name == 'svc02' && request.operation == 'UPDATE'
  allowedValues:
  - protected-service:true
