apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {name: optional-tls-ingress, namespace: team-a}
spec:
  tls:
  - hosts: [app.old.com, unchanged.example.com]
  - secretName: app.old.com
  - {}
