apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: prepend-registry-exception
  namespace: policy-exceptions
spec:
  policyRefs: [{kind: MutatingPolicy, name: prepend-registry}]
  matchConditions:
  - name: exact-resource
    expression: object.metadata.?namespace.orValue('') == '' && object.metadata.name == 'already-prefixed'
