apiVersion: policies.kyverno.io/v1
kind: PolicyException
metadata:
  name: deprecated-api-exception
  namespace: policy-exceptions
spec:
  policyRefs:
  - kind: ValidatingPolicy
    name: check-deprecated-apis
  allowedValues: [deprecated-api]
  matchConditions:
  - name: exact-resource
    expression: object.apiVersion == 'batch/v1beta1' && object.kind == 'CronJob' && object.metadata.name == 'exception-bad-cronjob' && object.metadata.namespace == 'test'
