apiVersion: v1
kind: Pod
metadata: {name: exception-net-raw, namespace: default}
spec:
  containers: [{name: app, image: gcr.io/google-samples/node-hello:1.0}]
---
apiVersion: v1
kind: Pod
metadata: {name: exception-net-raw, namespace: team-b}
spec:
  containers: [{name: app, image: gcr.io/google-samples/node-hello:1.0}]
